-- Q1) Revenue generated by male vs female customer 

		Select gender,sum(purchase_amount) as revenue 
		From customer
		Group by gender

		-- Female -> 75191 , Male -> 157890

-- Q2) Customers that used discount and still spent more than average purchase amount

		Select customer_id,purchase_amount
		From customer
		where discount_applied = 'Yes' and 
		purchase_amount >= (Select avg(purchase_amount) From customer)

		
-- Q3) Top 5 Product with highest average review rating 

		Select item_purchased,Round(sum(review_rating::numeric),2) as rating
		From customer
		Group by item_purchased 
		Order by rating desc
		Limit 5;

		-- Jewelry -> 642.80 , Pants -> 636.20 , Blouse -> 629.40 , Dress -> 622.40 , Sweater -> 616.60

-- Q4) compare the average purchase amounts between Standard and Express shipping

		Select shipping_type,Round(avg(purchase_amount),2) as avg_purchase_amount
		From customer
		Where shipping_type in ('Standard','Express')
		Group by shipping_type

		-- Standard -> 58.46 Express -> 60.48

-- Q5) Do subscribed customer spend more? compare average spend and total revenue(subscribed & unsubscribed)

		Select subscription_status,
			   count(customer_id) as total_customer,
			   Round(avg(purchase_amount),2) as average_spend,
			   Round(sum(purchase_amount),2) as total_revenue
		From customer 
		Group by subscription_status

		-- Unsubscribed -> 2847,59.87,170436.00 , Subscribed -> 1053,59.49,62645

-- Q6) Top 5 Product having highest percentage of purchases with discount applied

		Select item_purchased,
			   Round(sum(Case When discount_applied = 'Yes' then 1 else 0 end)*100/count(*),2) as discount_rate 
		from customer
		Group by item_purchased
		Order by discount_rate desc
		Limit 5;

		-- Hat -> 50.00 , Sneakers -> 49.00 , Coat -> 49.00 , Sweater -> 48.00 , Pants -> 47.00

--Q7) Segment customer i)New ii)Returning iii)Loyal based on their previous total purchase and show count.


		With customer_type as(
			Select customer_id,
				Case
					When previous_purchases = 1 then 'New'
					When previous_purchases between 2 and 10 then 'Returning'
					Else 'Loyal'
				End as customer_category	
			From customer )

		Select customer_category,count(*) as customers 
		From customer_type 
		Group by customer_category;

		-- Loyal -> 3116 , Returning -> 701 , New -> 83


-- Q8) Top 3 most purchased product in each category.

		With product_ranking as (
				Select category,item_purchased,count(*) as no_of_item,
				Row_Number() Over(Partition by Category Order by count(*) desc) as rank
				From customer
				Group by category,item_purchased 
				Order by category,rank 
		)
		Select rank,category,item_purchased,no_of_item
		From product_ranking
		Where rank <= 3;


-- Q9) Customers who are repeated buyers are subscribers or not.

		select subscription_status,count(customer_id) as repeated_buyers
		From customer
		where previous_purchases > 5
		Group by subscription_status;

		-- Subscribers -> 958 , Unsubscribers -> 2518

-- Q10) Revenue contribution of each age group 

		Select age_group,sum(purchase_amount) as total_revenue
		From customer
		Group by age_group
		Order by total_revenue desc;








Select * From customer;

Select count(distinct subscription_status) From customer;
